package com.umrah.api.service;

import com.razorpay.Order;
import com.razorpay.RazorpayClient;
import com.razorpay.RazorpayException;
import com.razorpay.Utils;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class RazorPayService {

    @Value("${razorpay.api.key}")
    private String apiKey;

    @Value("${razorpay.api.secret}")
    private String secret;

    public String getApiKey() {
        return apiKey;
    }

    /**
     * Create a Razorpay Order
     * @param amount Amount in INR (will be converted to paise)
     * @param currency Currency code (defaults to INR)
     * @param receiptId Unique receipt ID / reference
     * @return Created Razorpay Order
     * @throws RazorpayException If Razorpay API call fails
     */
    public Order createOrder(double amount, String currency, String receiptId) throws RazorpayException {
        RazorpayClient razorpayClient = new RazorpayClient(apiKey, secret);

        JSONObject orderRequest = new JSONObject();
        // Razorpay expects amount in smallest currency sub-unit (paise for INR)
        orderRequest.put("amount", (int) Math.round(amount * 100));
        orderRequest.put("currency", (currency != null && !currency.trim().isEmpty()) ? currency : "INR");
        orderRequest.put("receipt", receiptId);
        orderRequest.put("payment_capture", 1);

        return razorpayClient.orders.create(orderRequest);
    }

    /**
     * Verify Razorpay Payment Signature (HMAC-SHA256)
     * @param razorpayOrderId Order ID generated by Razorpay
     * @param razorpayPaymentId Payment ID returned after payment completion
     * @param razorpaySignature Signature returned after payment completion
     * @return true if valid signature, false otherwise
     */
    public boolean verifyPaymentSignature(String razorpayOrderId, String razorpayPaymentId, String razorpaySignature) {
        try {
            JSONObject options = new JSONObject();
            options.put("razorpay_order_id", razorpayOrderId);
            options.put("razorpay_payment_id", razorpayPaymentId);
            options.put("razorpay_signature", razorpaySignature);

            return Utils.verifyPaymentSignature(options, secret);
        } catch (Exception e) {
            return false;
        }
    }
}
